version: '3.4'
services:
  auth:
    container_name: auth
    environment:
      Authentication__Secret: "SHOULDBEINSECRETS"
    build:
      context: ./Auth
      dockerfile: ./Dockerfile
    ports:
      - "4001:80"
  api:
    container_name: api
    environment:
      Authentication__Secret: "SHOULDBEINSECRETS"
    build:
      context: ./Api
      dockerfile: ./Dockerfile
    ports:
      - "4002:80"
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
